### ISSUE TITLE
Links to websites of teammembers

### ISSUE THREAD

**Issue by vrom911** [kowainik/kowainik.github.io#79]
@kowainik/dev If you'd like me to add the link to your website, please provide the link in the comments 🙂

**Comment by ChShersh** [comment]
I would like to have my link on the website! Here is my personal blog:

* https://chshersh.github.io/

**Comment by kahlil29** [comment]
I don't have a personal website currently. 
I was trying to use jekyll and then came to know about hakyll from you guys, but never ended up making anything concrete. 
This is good motivation for me and I will try and get something simple and small done, maybe. 
If I do manage to do this, I will submit it to you guys. 

Btw have you guys checked out the `.dev` domains that recently opened up? 
I didn't feel it's worth purchasing for myself because I don't have a website, but since you guys do, maybe you would be interested! 😄

**Comment by kahlil29** [comment]
Also, I liked the very neat and clean UI/UX of your website @ChShersh  👍

**Comment by ChShersh** [comment]
@kahlil29 Thanks! My website is a simple bootstrap team. But @vrom911 helped me to make it look much better than standard template :slightly_smiling_face:

**Comment by qoelet** [comment]
@vrom911 I have a random blog/etc over at www.machinesung.com
